model: ReinflectionSeq2seq
dataset_class: ReinflectionDataset

lemma_embedding_size: 100
lemma_hidden_size: 512
lemma_num_layers: 3

tag_embedding_size: 50
tag_hidden_size: 256
tag_num_layers: 2

inflected_embedding_size: 100
inflected_hidden_size: 512
inflected_num_layers: 3

dropout: 0.2

use_eos: true

epochs: 200
batch_size: 32

early_stopping_strategy: dev_loss_increase

optimizer: Adam

experiment_dir: exps/task1/low_combined
save_min_epoch: 0
min_epochs: 20
