lemma_embedding_size: [20, 30, 50]
lemma_hidden_size: [512]
lemma_num_layers: [1, 2]

tag_embedding_size: [10, 20]
tag_hidden_size: [64, 128]
tag_num_layers: [1, 2]

inflected_embedding_size: [20, 30, 50]
inflected_hidden_size: [512]
inflected_num_layers: [1, 2]

dropout: [0.3, 0.4]
share_vocab: [true, false]
early_stopping_window: [5]
