batch_size: 128
dataset_class: ReinflectionDataset
dropout: 0.3
early_stopping_strategy: dev_loss_increase
early_stopping_window: 5
epochs: 200
experiment_dir: exps/task1/two_headed_best
inflected_embedding_size: 50
inflected_hidden_size: 256
inflected_num_layers: 2
language: breton
lemma_embedding_size: 20
lemma_hidden_size: 128
lemma_num_layers: 1
model: ReinflectionSeq2seq
optimizer: Adam
save_min_epoch: 0
share_embedding: false
share_vocab: false
tag_embedding_size: 10
tag_hidden_size: 128
tag_num_layers: 2
