batch_size: 128
commit_hash: b8047cbe58b4764127c40e16ce599b260c46dd30
dataset_class: ReinflectionDataset
dev_file: data/conll2018/task1/all/danish-dev
dropout: 0.3
early_stopping_window: 5
epochs: 200
inflected_embedding_size: 20
inflected_hidden_size: 256
inflected_num_layers: 2
lemma_embedding_size: 30
lemma_hidden_size: 512
lemma_num_layers: 4
model: ReinflectionSeq2seq
numpy_random_seed: 510766811
optimizer: Adam
save_min_epoch: 0
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 1
torch_random_seed: 1540495571
train_file: data/conll2018/task1/all/danish-train-high
