batch_size: 128
commit_hash: 818c7f814ba005b6165d3cca297ee3e4f58bc354
dataset_class: ReinflectionDataset
dev_file: data/conll2018/task1/surprise/french-dev
dropout: 0.3
early_stopping_window: 5
epochs: 200
inflected_embedding_size: 50
inflected_hidden_size: 256
inflected_num_layers: 2
lemma_embedding_size: 20
lemma_hidden_size: 128
lemma_num_layers: 1
model: ReinflectionSeq2seq
numpy_random_seed: 2099117257
optimizer: Adam
save_min_epoch: 0
share_vocab: false
tag_embedding_size: 10
tag_hidden_size: 128
tag_num_layers: 2
torch_random_seed: 644194696
train_file: data/conll2018/task1/surprise/french-train-medium
