batch_size: 128
commit_hash: f5ba7dc8958d998cae1372f78456fa82cfbf165e
dataset_class: ReinflectionDataset
dev_file: data/conll2018/task1/all/haida-dev
dropout: 0.4
early_stopping_window: 5
epochs: 200
inflected_embedding_size: 20
inflected_hidden_size: 512
inflected_num_layers: 2
lemma_embedding_size: 20
lemma_hidden_size: 512
lemma_num_layers: 4
model: ReinflectionSeq2seq
numpy_random_seed: 323473076
optimizer: Adam
save_min_epoch: 0
share_vocab: false
tag_embedding_size: 10
tag_hidden_size: 128
tag_num_layers: 2
torch_random_seed: 400196071
train_file: data/conll2018/task1/all/haida-train-low
