batch_size: 128
commit_hash: f5ba7dc8958d998cae1372f78456fa82cfbf165e
dataset_class: ReinflectionDataset
dropout: 0.3
early_stopping_window: 5
epochs: 200
inflected_embedding_size: 30
inflected_hidden_size: 512
inflected_num_layers: 2
lemma_embedding_size: 30
lemma_hidden_size: 512
lemma_num_layers: 1
model: ReinflectionSeq2seq
numpy_random_seed: 1955979529
optimizer: Adam
share_vocab: true
tag_embedding_size: 10
tag_hidden_size: 128
tag_num_layers: 1
torch_random_seed: 64202356
