batch_size: 128
commit_hash: 818c7f814ba005b6165d3cca297ee3e4f58bc354
dataset_class: ReinflectionDataset
dropout: 0.4
early_stopping_window: 5
epochs: 200
inflected_embedding_size: 30
inflected_hidden_size: 512
inflected_num_layers: 2
lemma_embedding_size: 10
lemma_hidden_size: 128
lemma_num_layers: 4
model: ReinflectionSeq2seq
numpy_random_seed: 1610214141
optimizer: Adam
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 3
torch_random_seed: 2016173275
