batch_size: 128
commit_hash: f5ba7dc8958d998cae1372f78456fa82cfbf165e
dataset_class: ReinflectionDataset
dropout: 0.1
early_stopping_window: 5
epochs: 200
inflected_embedding_size: 20
inflected_hidden_size: 256
inflected_num_layers: 1
lemma_embedding_size: 20
lemma_hidden_size: 512
lemma_num_layers: 2
model: ReinflectionSeq2seq
numpy_random_seed: 394821188
optimizer: Adam
share_vocab: true
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 4
torch_random_seed: 835991687
