batch_size: 128
commit_hash: 68f9be08055284a4cbcfa6070b64d1663dab6940
dataset_class: ReinflectionDataset
dropout: 0.3
early_stopping_window: 5
epochs: 200
inflected_embedding_size: 20
inflected_hidden_size: 256
inflected_num_layers: 2
lemma_embedding_size: 30
lemma_hidden_size: 512
lemma_num_layers: 4
model: ReinflectionSeq2seq
numpy_random_seed: 1723606450
optimizer: Adam
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 1
torch_random_seed: 167280880
