batch_size: 128
commit_hash: 88a0cd8b5bd391b6cfaf16a9d7c6583efcf9795f
dataset_class: ReinflectionDataset
dev_file: data/conll2018/task1/all/slovene-dev
dropout: 0.3
early_stopping_window: 5
epochs: 200
inflected_embedding_size: 20
inflected_hidden_size: 1024
inflected_num_layers: 2
lemma_embedding_size: 20
lemma_hidden_size: 1024
lemma_num_layers: 1
model: ReinflectionSeq2seq
numpy_random_seed: 306029340
optimizer: Adam
save_min_epoch: 0
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 2
torch_random_seed: 1445567107
train_file: data/conll2018/task1/all/slovene-train-medium
