batch_size: 128
commit_hash: 88a0cd8b5bd391b6cfaf16a9d7c6583efcf9795f
dataset_class: ReinflectionDataset
dropout: 0.4
early_stopping_window: 5
epochs: 200
inflected_embedding_size: 20
inflected_hidden_size: 512
inflected_num_layers: 2
lemma_embedding_size: 20
lemma_hidden_size: 512
lemma_num_layers: 4
model: ReinflectionSeq2seq
numpy_random_seed: 896908732
optimizer: Adam
share_vocab: false
tag_embedding_size: 10
tag_hidden_size: 128
tag_num_layers: 2
torch_random_seed: 1199714180
