batch_size: 32
char_embedding_size: 50
commit_hash: d9c609a11a273f16733a7c2bd60be3791e0f3e3c
context_hidden_size: 256
context_num_layers: 2
dataset_class: SIGMORPHONTask2Track2Dataset
decoder_num_layers: 2
dev_file: data/conll2018/task2/devsets/en-uncovered
dropout: 0.2
early_stopping_window: 5
epochs: 200
include_same_forms_ratio: 0.0
lemma_hidden_size: 256
lemma_num_layers: 2
min_epochs: 0
model: Task2Track2Model
numpy_random_seed: 46692631
optimizer: Adam
save_min_epoch: 0
share_context_encoder: false
share_embedding: true
share_vocab: true
torch_random_seed: 397873126
train_file: data/conll2018/task2/trainsets/en-track2-low
word_hidden_size: 256
word_num_layers: 2
