batch_size: 16
char_embedding_size: 40
commit_hash: f5ba7dc8958d998cae1372f78456fa82cfbf165e
context_hidden_size: 256
context_num_layers: 2
dataset_class: SIGMORPOHTask2Track1Dataset
decoder_hidden_size: 256
decoder_num_layers: 2
dev_file: data/conll2018/task2/devsets/de-uncovered
dropout: 0.2
early_stopping_window: 5
epochs: 200
include_same_forms_ratio: 1.0
lemma_hidden_size: 256
lemma_num_layers: 2
min_epochs: 0
model: ContextInflectionSeq2seq
numpy_random_seed: 2000960677
optimizer: Adam
save_min_epoch: 0
share_context_encoder: false
share_embedding: false
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 2
torch_random_seed: 1465103572
train_file: data/conll2018/task2/trainsets/de-track1-high
word_hidden_size: 256
word_num_layers: 2
