batch_size: 32
char_embedding_size: 40
commit_hash: a5c83b8eccd0becea5faab3e15ddd45accca7944
context_hidden_size: 256
context_num_layers: 1
dataset_class: SIGMORPOHTask2Track1Dataset
decoder_hidden_size: 256
decoder_num_layers: 1
dev_file: data/conll2018/task2/devsets/en-uncovered
dropout: 0.0
early_stopping_window: 5
epochs: 200
include_same_forms_ratio: 1.0
lemma_hidden_size: 256
lemma_num_layers: 1
min_epochs: 0
model: ContextInflectionSeq2seq
numpy_random_seed: 627680263
optimizer: Adam
save_min_epoch: 0
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 1
torch_random_seed: 693541006
train_file: data/conll2018/task2/trainsets/en-track1-high
word_hidden_size: 256
word_num_layers: 1
