batch_size: 16
char_embedding_size: 40
commit_hash: be844cc98b151054ad0ef5b1a2848d14f8d07c3b
context_hidden_size: 256
context_num_layers: 1
dataset_class: SIGMORPOHTask2Track1Dataset
decoder_hidden_size: 256
decoder_num_layers: 1
dev_file: data/conll2018/task2/devsets/en-uncovered
dropout: 0.4
epochs: 200
include_same_forms_ratio: 1.0
lemma_hidden_size: 256
lemma_num_layers: 1
model: ContextInflectionSeq2seq
numpy_random_seed: 1727607719
optimizer: Adam
save_min_epoch: 0
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 1
torch_random_seed: 1460525910
train_file: data/conll2018/task2/trainsets/en-track1-low
word_hidden_size: 256
word_num_layers: 1
