batch_size: 8
char_embedding_size: 30
commit_hash: 818c7f814ba005b6165d3cca297ee3e4f58bc354
context_hidden_size: 64
context_num_layers: 2
dataset_class: SIGMORPOHTask2Track1Dataset
decoder_hidden_size: 64
decoder_num_layers: 1
dev_file: data/conll2018/task2/devsets/fr-uncovered
dropout: 0.2
early_stopping_window: 10
epochs: 200
include_same_forms_ratio: 1.0
lemma_hidden_size: 256
lemma_num_layers: 1
min_epochs: 0
model: ContextInflectionSeq2seq
numpy_random_seed: 338278908
optimizer: Adam
save_min_epoch: 0
share_embedding: false
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 1
torch_random_seed: 1421675902
train_file: data/conll2018/task2/trainsets/fr-track1-medium
word_hidden_size: 64
word_num_layers: 2
