batch_size: 16
char_embedding_size: 40
commit_hash: 88a0cd8b5bd391b6cfaf16a9d7c6583efcf9795f
context_hidden_size: 256
context_num_layers: 2
dataset_class: SIGMORPOHTask2Track1Dataset
decoder_hidden_size: 256
decoder_num_layers: 2
dev_file: data/conll2018/task2/devsets/ru-uncovered
dropout: 0.2
early_stopping_window: 5
epochs: 200
include_same_forms_ratio: 1.0
lemma_hidden_size: 256
lemma_num_layers: 2
min_epochs: 0
model: ContextInflectionSeq2seq
numpy_random_seed: 703887179
optimizer: Adam
save_min_epoch: 0
share_context_encoder: false
share_embedding: false
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 2
torch_random_seed: 626869656
train_file: data/conll2018/task2/trainsets/ru-track1-high
word_hidden_size: 256
word_num_layers: 2
