batch_size: 16
char_embedding_size: 40
commit_hash: 2cccbc9dae4ab04eac491a3fe3fe02d7f1ed581b
context_hidden_size: 128
context_num_layers: 1
dataset_class: SIGMORPOHTask2Track1Dataset
decoder_hidden_size: 128
decoder_num_layers: 1
dev_file: data/conll2018/task2/devsets/ru-uncovered
dropout: 0.0
epochs: 200
include_same_forms_ratio: 1.0
lemma_hidden_size: 128
lemma_num_layers: 1
model: ContextInflectionSeq2seq
numpy_random_seed: 253202341
optimizer: Adam
save_min_epoch: 0
share_vocab: false
tag_embedding_size: 20
tag_hidden_size: 128
tag_num_layers: 1
torch_random_seed: 145362913
train_file: data/conll2018/task2/trainsets/ru-track1-medium
word_hidden_size: 128
word_num_layers: 1
