model: LuongAttentionSeq2seq
dataset_class: SIGMORPOHTask1Dataset
embedding_size_src: 30
embedding_size_tgt: 30
hidden_size: 64
num_layers_src: 1
num_layers_tgt: 1
dropout: 0.3

use_eos: true

epochs: 200
batch_size: 128

early_stopping_ratio: 1.5

optimizer: Adam

experiment_dir: exps/task1/luong_param_search
save_min_epoch: 0
min_epochs: 20
